import os
import json
from dotenv import load_dotenv
from openai import OpenAI
from datetime import datetime

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def get_subject_path():
    path = os.path.join(os.path.expanduser("~"), ".opentrace", "subject.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path

def load_subject():
    with open(get_subject_path(), "r") as f:
        return json.load(f)

def load_json(filename):
    if not os.path.exists(filename):
        print(f"⚠️ Missing: {filename}")
        return []
    with open(filename, "r") as f:
        return json.load(f)

def format_section(title, items):
    section = f"\n## {title}\n"
    if not items:
        return section + "_No findings available._\n"
    for i, item in enumerate(items, 1):
        section += f"\n### {i}. {item.get('title', item.get('breach', 'Untitled'))}\n"
        section += f"{item.get('summary', '')}\n"
        if "url" in item:
            section += f"[Source]({item['url']})\n"
        section += f"**Reliability**: {item.get('reliability', 'Unknown')}  \n"
        section += f"**Confidence**: {item.get('confidence', 'Not rated')}\n"
    return section

def generate_exec_summary(subject, sources):
    findings = "\n\n".join([item.get("summary", "") for section in sources for item in section])
    prompt = f"""You are an OSINT analyst. Write a 150–200 word executive summary assessing digital, reputational, and political risk for {subject['name']}.
Findings:
{findings}
"""
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

if __name__ == "__main__":
    subject = load_subject()
    print(f"📄 Generating report for: {subject['name']}")

    news = load_json("report_newsapi.json")
    hibp = load_json("report_hibp.json")
    google = load_json("report_google_twitter.json")
    reddit = load_json("report_reddit.json")

    summary = generate_exec_summary(subject, [news, hibp, google, reddit])

    now = datetime.now()
    ts = now.strftime("%Y%m%d_%H%M")
    readable_ts = now.strftime("%Y-%m-%d %H:%M")

    report = f"# Protection Briefing: {subject['name']}\n"
    report += "_Generated by OpenTrace_\n\n"
    report += f"**Generated on:** {readable_ts}\n\n"

    report += "## Subject Profile\n"
    report += json.dumps(subject, indent=2) + "\n"

    report += "\n## Executive Summary\n" + summary + "\n"
    report += format_section("Media Coverage (NewsAPI)", news)
    report += format_section("Breach Exposure (HIBP)", hibp)
    report += format_section("Mentions on Twitter (Google)", google)
    report += format_section("Mentions on Reddit", reddit)

    try:
        with open("disclaimer.md", "r") as f:
            report += "\n" + f.read()
    except FileNotFoundError:
        report += "\n\n_Disclaimer missing._"

    os.makedirs("reports", exist_ok=True)
    parts = subject["name"].lower().split()
    filename = f"reports/{parts[-1]}_{parts[0]}_{ts}.md"

    with open(filename, "w") as f:
        f.write(report)

    print(f"✅ Report saved: {filename}")